name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 수동 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build and Deploy with Docker
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
        run: |
          docker build -t flask-app .
          docker stop flask-app || true
          docker rm flask-app || true
          docker run -d --name flask-app -p 5000:5000 flask-app